language: python

cache:
  directories:
  - "~/.platformio"

install:
  - pip install -U platformio


env:
  - PLATFORMIO_CI_SRC=examples/Button/Button.cpp

script:
  - platformio ci --board=uno --lib="."

