language: python

cache:
  directories:
  - "~/.platformio"

install:
  - pip install -U platformio


env:
  - PLATFORMIO_CI_SRC=examples/Button/Button

script:
  - platformio ci --board=uno --board=teensy31 --board=due --lib="."

